name: Deploy Website

on:
  push:
    branches:
      - main  # สาขาที่จะ trigger deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. เช็คเอา repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. ติดตั้ง Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. ติดตั้ง dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build โปรเจกต์
      - name: Build
        run: npm run build

      # 5. Deploy ขึ้น GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/spa  # ปรับ path ให้ตรงกับ build output ของคุณ