# .github/workflows/playwright-test.yml
name: Playwright Test

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run Playwright tests
        run: npx playwright test --reporter=list
      - name: Upload Playwright results
        uses: actions/upload-artifact@v3
        with:
          name: playwright-results
          path: tests/playwright-report/